import { useState } from "react";
import { ToolLayout } from "@/components/ToolLayout";
import { toast } from "sonner";
import { motion, AnimatePresence } from "framer-motion";
import { Globe, Search, Copy, Download, Server, Shield, Mail, MapPin, Clock, Loader2, RefreshCw, Sparkles, Zap } from "lucide-react";

interface DnsRecord {
  type: string;
  name: string;
  value: string;
  ttl?: number;
}

export default function DnsLookup() {
  const [domain, setDomain] = useState("");
  const [records, setRecords] = useState<DnsRecord[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [selectedType, setSelectedType] = useState("ALL");
  const [history, setHistory] = useState<{ domain: string; time: string; count: number }[]>([]);

  const recordTypes = ["ALL", "A", "AAAA", "CNAME", "MX", "NS", "TXT", "SOA", "SRV", "CAA"];

  const typeColors: Record<string, string> = {
    A: "from-blue-500 to-cyan-500",
    AAAA: "from-purple-500 to-violet-500",
    CNAME: "from-green-500 to-emerald-500",
    MX: "from-orange-500 to-amber-500",
    NS: "from-pink-500 to-rose-500",
    TXT: "from-yellow-500 to-lime-500",
    SOA: "from-red-500 to-orange-500",
    SRV: "from-indigo-500 to-blue-500",
    CAA: "from-teal-500 to-cyan-500",
  };

  const typeIcons: Record<string, any> = {
    A: MapPin, AAAA: MapPin, CNAME: Globe, MX: Mail, NS: Server,
    TXT: Shield, SOA: Clock, SRV: Server, CAA: Shield,
  };

  const lookup = async () => {
    const d = domain.trim().replace(/^https?:\/\//, "").replace(/\/.*/, "");
    if (!d) { toast.error("Enter a domain name"); return; }
    setLoading(true); setError(""); setRecords([]);

    try {
      const types = selectedType === "ALL" ? ["A", "AAAA", "CNAME", "MX", "NS", "TXT"] : [selectedType];
      const allRecords: DnsRecord[] = [];

      for (const type of types) {
        try {
          const res = await fetch(`https://dns.google/resolve?name=${d}&type=${type}`);
          const data = await res.json();
          if (data.Answer) {
            for (const ans of data.Answer) {
              const rType = { 1: "A", 28: "AAAA", 5: "CNAME", 15: "MX", 2: "NS", 16: "TXT", 6: "SOA", 33: "SRV", 257: "CAA" }[ans.type] || type;
              allRecords.push({ type: rType, name: ans.name, value: ans.data, ttl: ans.TTL });
            }
          }
        } catch { /* skip failed type */ }
      }

      if (allRecords.length === 0) {
        setError("No DNS records found for this domain");
      } else {
        setRecords(allRecords);
        setHistory(prev => [{ domain: d, time: new Date().toLocaleTimeString(), count: allRecords.length }, ...prev.filter(h => h.domain !== d)].slice(0, 10));
        toast.success(`Found ${allRecords.length} DNS records!`);
      }
    } catch (err: any) {
      setError(err.message || "Lookup failed");
      toast.error("DNS lookup failed");
    }
    setLoading(false);
  };

  const copy = (text: string) => { navigator.clipboard.writeText(text); toast.success("Copied!"); };

  const exportRecords = () => {
    const lines = [`DNS Records for ${domain}`, `Generated: ${new Date().toISOString()}`, "", "Type | Name | Value | TTL", "--- | --- | --- | ---",
      ...records.map(r => `${r.type} | ${r.name} | ${r.value} | ${r.ttl || "N/A"}`), "", "Generated by Makursite"];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = `dns-${domain}.txt`; a.click();
    toast.success("Report exported!");
  };

  const grouped = records.reduce((acc, r) => { (acc[r.type] = acc[r.type] || []).push(r); return acc; }, {} as Record<string, DnsRecord[]>);

  return (
    <ToolLayout title="DNS Lookup" description="Look up DNS records for any domain — A, AAAA, MX, CNAME, NS, TXT & more">
      <div className="space-y-6 max-w-3xl mx-auto">
        {/* Header */}
        <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }}
          className="tool-section-card p-6 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-gradient-to-r from-cyan-500/20 to-blue-500/20 border border-cyan-500/30 mb-3">
            <Server className="w-5 h-5 text-cyan-400" />
            <span className="text-sm font-bold text-cyan-400">DNS Record Analyzer</span>
          </div>
          <h2 className="text-2xl font-black gradient-text">Comprehensive DNS Lookup</h2>
          <p className="text-muted-foreground text-sm mt-1">Query DNS records using Google Public DNS</p>
        </motion.div>

        {/* Input */}
        <div className="tool-section-card p-4 space-y-3">
          <div className="flex gap-2">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <input value={domain} onChange={e => setDomain(e.target.value)}
                placeholder="example.com" onKeyDown={e => e.key === "Enter" && lookup()}
                className="tool-input-colorful w-full rounded-xl pl-10 pr-3 py-2.5 font-mono text-sm" />
            </div>
            <button onClick={lookup} disabled={loading} className="tool-btn-primary shrink-0 px-5 py-2.5 flex items-center gap-1.5 text-sm disabled:opacity-50">
              {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Zap className="w-4 h-4" />} Lookup
            </button>
          </div>
          {/* Type selector */}
          <div className="flex flex-wrap gap-1.5">
            {recordTypes.map(t => (
              <button key={t} onClick={() => setSelectedType(t)}
                className={`px-2.5 py-1 rounded-full text-xs font-bold transition-all ${selectedType === t ? "bg-primary text-primary-foreground shadow-lg shadow-primary/30" : "bg-muted text-muted-foreground hover:bg-muted/80"}`}>
                {t}
              </button>
            ))}
          </div>
        </div>

        {error && <div className="text-destructive bg-destructive/10 rounded-xl p-4 text-sm border border-destructive/20">{error}</div>}

        {/* Results */}
        <AnimatePresence>
          {records.length > 0 && (
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="space-y-4">
              {/* Summary */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                {Object.entries(grouped).map(([type, recs], i) => {
                  const Icon = typeIcons[type] || Globe;
                  return (
                    <motion.div key={type} initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: i * 0.05 }}
                      className="tool-stat-card p-3 text-center">
                      <div className={`w-8 h-8 mx-auto rounded-lg bg-gradient-to-br ${typeColors[type] || "from-gray-500 to-slate-500"} flex items-center justify-center mb-1.5`}>
                        <Icon className="w-4 h-4 text-white" />
                      </div>
                      <div className="text-lg font-black">{recs.length}</div>
                      <div className="text-[10px] text-muted-foreground font-bold uppercase">{type} Records</div>
                    </motion.div>
                  );
                })}
              </div>

              {/* Records by type */}
              {Object.entries(grouped).map(([type, recs]) => {
                const Icon = typeIcons[type] || Globe;
                return (
                  <div key={type} className="tool-section-card overflow-hidden">
                    <div className={`p-3 bg-gradient-to-r ${typeColors[type] || "from-gray-500/10 to-slate-500/10"} bg-opacity-10 border-b border-border/30 flex items-center gap-2`}>
                      <div className={`w-6 h-6 rounded-lg bg-gradient-to-br ${typeColors[type] || "from-gray-500 to-slate-500"} flex items-center justify-center`}>
                        <Icon className="w-3 h-3 text-white" />
                      </div>
                      <span className="text-sm font-bold">{type} Records ({recs.length})</span>
                    </div>
                    <div className="divide-y divide-border/20">
                      {recs.map((r, i) => (
                        <motion.div key={i} initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: i * 0.03 }}
                          className="p-3 hover:bg-accent/10 transition-colors cursor-pointer group" onClick={() => copy(r.value)}>
                          <div className="flex items-center justify-between gap-2">
                            <div className="min-w-0 flex-1">
                              <div className="text-xs text-muted-foreground font-mono truncate">{r.name}</div>
                              <div className="text-sm font-bold font-mono truncate mt-0.5">{r.value}</div>
                            </div>
                            <div className="flex items-center gap-2 shrink-0">
                              {r.ttl && <span className="text-[10px] text-muted-foreground bg-muted px-1.5 py-0.5 rounded">{r.ttl}s</span>}
                              <Copy className="w-3.5 h-3.5 text-muted-foreground opacity-0 group-hover:opacity-100 transition-opacity" />
                            </div>
                          </div>
                        </motion.div>
                      ))}
                    </div>
                  </div>
                );
              })}

              <button onClick={exportRecords} className="tool-btn-primary w-full py-3 flex items-center justify-center gap-2 font-bold text-sm">
                <Download className="w-4 h-4" /> Export DNS Report
              </button>
            </motion.div>
          )}
        </AnimatePresence>

        {/* History */}
        {history.length > 0 && (
          <div className="tool-section-card overflow-hidden">
            <div className="p-3 bg-accent/30 border-b border-border/30 flex items-center justify-between">
              <span className="text-xs font-bold flex items-center gap-1.5"><RefreshCw className="w-3 h-3" /> Lookup History</span>
              <button onClick={() => setHistory([])} className="text-xs text-muted-foreground hover:text-foreground">Clear</button>
            </div>
            <div className="divide-y divide-border/20">
              {history.map((h, i) => (
                <button key={i} onClick={() => { setDomain(h.domain); }}
                  className="w-full flex items-center gap-3 px-3 py-2 text-xs hover:bg-accent/10 transition-colors">
                  <Globe className="w-3 h-3 text-primary shrink-0" />
                  <span className="font-mono font-bold">{h.domain}</span>
                  <span className="text-muted-foreground">{h.count} records</span>
                  <span className="text-muted-foreground/50 ml-auto">{h.time}</span>
                </button>
              ))}
            </div>
          </div>
        )}
      </div>
    </ToolLayout>
  );
}
