import { useState, useRef } from "react";
import { ToolLayout } from "@/components/ToolLayout";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export default function FacebookIdCard() {
  const [name, setName] = useState("John Doe");
  const [username, setUsername] = useState("johndoe");
  const [bio, setBio] = useState("Web Developer | Tech Enthusiast");
  const [friends, setFriends] = useState("1,234");
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const generate = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    canvas.width = 500;
    canvas.height = 280;
    // BG
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, 500, 280);
    // Header bar
    ctx.fillStyle = "#1877f2";
    ctx.fillRect(0, 0, 500, 60);
    ctx.fillStyle = "#fff";
    ctx.font = "bold 22px sans-serif";
    ctx.fillText("facebook", 20, 40);
    // Avatar placeholder
    ctx.fillStyle = "#e4e6eb";
    ctx.beginPath();
    ctx.arc(60, 120, 35, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = "#999";
    ctx.font = "10px sans-serif";
    ctx.textAlign = "center";
    ctx.fillText("Photo", 60, 124);
    // Info
    ctx.textAlign = "left";
    ctx.fillStyle = "#050505";
    ctx.font = "bold 18px sans-serif";
    ctx.fillText(name, 110, 105);
    ctx.fillStyle = "#65676b";
    ctx.font = "13px sans-serif";
    ctx.fillText(`@${username}`, 110, 125);
    ctx.fillText(bio, 110, 148);
    ctx.fillStyle = "#1877f2";
    ctx.font = "bold 14px sans-serif";
    ctx.fillText(`${friends} Friends`, 110, 175);
    // Footer
    ctx.fillStyle = "#e4e6eb";
    ctx.fillRect(0, 220, 500, 60);
    ctx.fillStyle = "#65676b";
    ctx.font = "10px sans-serif";
    ctx.textAlign = "center";
    ctx.fillText("Facebook ID Card — Generated by WebTools", 250, 255);
  };

  const download = () => {
    generate();
    setTimeout(() => {
      const link = document.createElement("a");
      link.download = "facebook-id-card.png";
      link.href = canvasRef.current?.toDataURL() || "";
      link.click();
    }, 100);
  };

  return (
    <ToolLayout title="Facebook ID Card Maker" description="Create Facebook-style ID cards">
      <div className="space-y-5 max-w-lg mx-auto">
        <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Full Name" className="rounded-xl" />
        <Input value={username} onChange={(e) => setUsername(e.target.value)} placeholder="Username" className="rounded-xl" />
        <Input value={bio} onChange={(e) => setBio(e.target.value)} placeholder="Bio" className="rounded-xl" />
        <Input value={friends} onChange={(e) => setFriends(e.target.value)} placeholder="Friends Count" className="rounded-xl" />
        <div className="flex gap-3">
          <Button onClick={generate} className="gradient-bg text-primary-foreground rounded-xl font-semibold">Preview</Button>
          <Button onClick={download} variant="outline" className="rounded-xl">Download</Button>
        </div>
        <canvas ref={canvasRef} className="w-full rounded-2xl border border-border" />
      </div>
    </ToolLayout>
  );
}
