import { useState } from "react";
import { ToolLayout } from "@/components/ToolLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { motion, AnimatePresence } from "framer-motion";
import { Globe, MapPin, Building, Wifi, Shield, Clock, Copy, Search, Download, Loader2, RefreshCw } from "lucide-react";

interface IpInfo {
  ip: string;
  city: string;
  region: string;
  country: string;
  loc: string;
  org: string;
  timezone: string;
  postal: string;
  hostname?: string;
}

export default function IpAddressLookup() {
  const [ip, setIp] = useState("");
  const [info, setInfo] = useState<IpInfo | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [history, setHistory] = useState<{ ip: string; country: string; time: string }[]>([]);

  const lookup = async (customIp?: string) => {
    setLoading(true);
    setError("");
    setInfo(null);
    try {
      const target = customIp ?? ip.trim();
      const url = target ? `https://ipinfo.io/${target}/json` : `https://ipinfo.io/json`;
      const res = await fetch(url);
      if (!res.ok) throw new Error("Could not fetch IP info");
      const data = await res.json();
      if (data.bogon) throw new Error("This is a private/bogon IP address");
      setInfo(data);
      if (!customIp && !ip.trim()) setIp(data.ip);

      const entry = { ip: data.ip, country: data.country || "?", time: new Date().toLocaleTimeString() };
      setHistory(prev => [entry, ...prev.filter(h => h.ip !== data.ip)].slice(0, 10));
      toast.success("IP lookup complete!");
    } catch (err: any) {
      setError(err.message || "Lookup failed");
      toast.error("Lookup failed");
    }
    setLoading(false);
  };

  const copy = (text: string) => {
    navigator.clipboard.writeText(text);
    toast.success("Copied!");
  };

  const exportReport = () => {
    if (!info) return;
    const lines = [
      `IP Address Report`,
      `Generated: ${new Date().toISOString()}`,
      ``,
      `IP: ${info.ip}`,
      `Location: ${info.city}, ${info.region}`,
      `Country: ${info.country}`,
      `ISP: ${info.org}`,
      `Timezone: ${info.timezone}`,
      `Postal: ${info.postal}`,
      `Coordinates: ${info.loc}`,
      ``,
      `Generated by Cyber Venom Tools`
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `ip-report-${info.ip}.txt`;
    a.click();
    toast.success("Report downloaded!");
  };

  const cards = info ? [
    { icon: Globe, label: "IP Address", value: info.ip, color: "text-blue-500" },
    { icon: MapPin, label: "City", value: info.city || "N/A", color: "text-green-500" },
    { icon: Building, label: "Region", value: info.region || "N/A", color: "text-purple-500" },
    { icon: Shield, label: "Country", value: info.country || "N/A", color: "text-orange-500" },
    { icon: Wifi, label: "ISP / Org", value: info.org || "N/A", color: "text-cyan-500" },
    { icon: Clock, label: "Timezone", value: info.timezone || "N/A", color: "text-yellow-500" },
    { icon: MapPin, label: "Postal Code", value: info.postal || "N/A", color: "text-pink-500" },
    { icon: Globe, label: "Coordinates", value: info.loc || "N/A", color: "text-indigo-500" },
  ] : [];

  return (
    <ToolLayout title="IP Address Lookup" description="Find geolocation, ISP, timezone and more for any IP address">
      <div className="space-y-6 max-w-2xl mx-auto">
        {/* Input */}
        <div className="flex gap-2">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input
              value={ip}
              onChange={e => setIp(e.target.value)}
              placeholder="Enter IP address (or leave empty for your IP)"
              className="rounded-xl flex-1 pl-10 font-mono"
              onKeyDown={e => e.key === "Enter" && lookup()}
            />
          </div>
          <button onClick={() => lookup()} disabled={loading} className="tool-btn-primary shrink-0 px-5 py-2.5 flex items-center gap-1.5 text-sm disabled:opacity-50">
            {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Search className="w-4 h-4" />}
            Lookup
          </button>
        </div>

        <Button variant="outline" className="rounded-xl gap-1.5" onClick={() => lookup("")} disabled={loading}>
          <Globe className="w-4 h-4" /> Find My IP Address
        </Button>

        {error && (
          <div className="text-destructive bg-destructive/10 rounded-xl p-4 text-sm border border-destructive/20">{error}</div>
        )}

        <AnimatePresence>
          {info && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              className="space-y-4"
            >
              {/* IP Header */}
              <div className="tool-result-card text-center">
                <p className="text-xs text-muted-foreground font-semibold uppercase tracking-wider">IP Address</p>
                <p className="text-3xl font-black text-primary mt-1 font-mono">{info.ip}</p>
                <p className="text-sm text-muted-foreground mt-1">{info.city}, {info.region}, {info.country}</p>
                <div className="flex gap-2 justify-center mt-3">
                  <Button size="sm" variant="outline" className="rounded-lg gap-1" onClick={() => copy(info.ip)}>
                    <Copy className="w-3 h-3" /> Copy IP
                  </Button>
                  <Button size="sm" variant="outline" className="rounded-lg gap-1" onClick={exportReport}>
                    <Download className="w-3 h-3" /> Export
                  </Button>
                </div>
              </div>

              {/* Info Cards */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                {cards.map((c, i) => (
                  <motion.div
                    key={c.label}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: i * 0.05 }}
                    className="bg-card rounded-xl border border-border/30 p-3 hover:border-primary/30 transition-colors group cursor-pointer"
                    onClick={() => copy(c.value)}
                  >
                    <c.icon className={`w-4 h-4 ${c.color} mb-1.5 group-hover:scale-110 transition-transform`} />
                    <div className="text-[10px] text-muted-foreground font-semibold uppercase tracking-wider">{c.label}</div>
                    <div className="text-sm font-bold mt-0.5 truncate">{c.value}</div>
                  </motion.div>
                ))}
              </div>

              {/* Map */}
              {info.loc && (
                <div className="rounded-xl overflow-hidden border border-border/50">
                  <iframe
                    title="Location Map"
                    width="100%"
                    height="300"
                    style={{ border: 0 }}
                    loading="lazy"
                    src={`https://www.openstreetmap.org/export/embed.html?bbox=${
                      Number(info.loc.split(",")[1]) - 0.05
                    },${Number(info.loc.split(",")[0]) - 0.05},${
                      Number(info.loc.split(",")[1]) + 0.05
                    },${Number(info.loc.split(",")[0]) + 0.05}&layer=mapnik&marker=${info.loc}`}
                  />
                </div>
              )}
            </motion.div>
          )}
        </AnimatePresence>

        {/* History */}
        {history.length > 0 && (
          <div className="rounded-xl border border-border/30 bg-card overflow-hidden">
            <div className="p-3 bg-accent/30 border-b border-border/30 flex items-center justify-between">
              <span className="text-xs font-bold">📋 Lookup History</span>
              <Button variant="ghost" size="sm" className="h-6 text-xs" onClick={() => setHistory([])}>Clear</Button>
            </div>
            <div className="divide-y divide-border/20">
              {history.map((h, i) => (
                <button key={i} onClick={() => { setIp(h.ip); lookup(h.ip); }}
                  className="w-full flex items-center gap-3 px-3 py-2 text-xs hover:bg-accent/10 transition-colors">
                  <span className="font-mono font-bold">{h.ip}</span>
                  <span className="text-muted-foreground">{h.country}</span>
                  <span className="text-muted-foreground/50 ml-auto">{h.time}</span>
                </button>
              ))}
            </div>
          </div>
        )}
      </div>
    </ToolLayout>
  );
}
