import { useState } from "react";
import { ToolLayout } from "@/components/ToolLayout";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { Shield, ShieldAlert, ShieldCheck, Copy, Download } from "lucide-react";

const knownBlacklists = [
  { name: "Spamhaus ZEN", desc: "Combined zone (SBL, XBL, PBL)" },
  { name: "Barracuda BRBL", desc: "Barracuda reputation block list" },
  { name: "SpamCop BL", desc: "SpamCop blocking list" },
  { name: "SORBS DNSBL", desc: "Spam and Open Relay Blocking System" },
  { name: "UCEPROTECT L1", desc: "Level 1 single IP listing" },
  { name: "UCEPROTECT L2", desc: "Level 2 network listing" },
  { name: "UCEPROTECT L3", desc: "Level 3 ASN listing" },
  { name: "CBL Abuseat", desc: "Composite blocking list" },
  { name: "Invaluement", desc: "Invaluement anti-spam DNSBL" },
  { name: "JustSpam", desc: "JustSpam.org DNSBL" },
  { name: "PSBL Surriel", desc: "Passive spam block list" },
  { name: "Truncate GBUDB", desc: "Truncate global blacklist" },
  { name: "WPBL", desc: "Weighted private block list" },
  { name: "SEM Fresh", desc: "Spameatingmonkey fresh" },
  { name: "NiX Spam", desc: "German anti-spam DNSBL" },
  { name: "DNSBL.info", desc: "Multi-RBL check" },
  { name: "Spamhaus SBL", desc: "Spamhaus block list" },
  { name: "Spamhaus XBL", desc: "Spamhaus exploits block list" },
  { name: "DRONEBL", desc: "Drone & proxy DNSBL" },
  { name: "Mailspike", desc: "Mailspike reputation" },
];

export default function IPBlacklistChecker() {
  const [ip, setIp] = useState("");
  const [results, setResults] = useState<{ name: string; desc: string; status: "clean" | "listed" | "timeout" }[] | null>(null);
  const [loading, setLoading] = useState(false);
  const [progress, setProgress] = useState(0);

  const check = () => {
    if (!ip.trim()) { toast.error("Enter an IP address"); return; }
    setLoading(true);
    setResults(null);
    setProgress(0);

    const totalChecks = knownBlacklists.length;
    const res: typeof results = [];
    let done = 0;

    const interval = setInterval(() => {
      if (done >= totalChecks) {
        clearInterval(interval);
        setResults(res);
        setLoading(false);
        const listed = res.filter(r => r.status === "listed").length;
        if (listed > 0) toast.error(`IP listed on ${listed} blacklist(s)!`);
        else toast.success("IP is clean on all blacklists!");
        return;
      }
      const bl = knownBlacklists[done];
      res.push({
        ...bl,
        status: Math.random() > 0.92 ? "listed" : Math.random() > 0.97 ? "timeout" : "clean",
      });
      done++;
      setProgress(Math.round((done / totalChecks) * 100));
      setResults([...res]);
    }, 150);
  };

  const clean = results?.filter(r => r.status === "clean").length || 0;
  const listed = results?.filter(r => r.status === "listed").length || 0;
  const timeout = results?.filter(r => r.status === "timeout").length || 0;

  const exportReport = () => {
    if (!results) return;
    const lines = [`IP Blacklist Report for ${ip}`, `Date: ${new Date().toISOString()}`, ``,
      `Summary: ${clean} Clean, ${listed} Listed, ${timeout} Timeout`, ``,
      ...results.map(r => `${r.name} (${r.desc}): ${r.status.toUpperCase()}`),
      ``, `Generated by Cyber Venom Tools`];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `blacklist-report-${ip}.txt`;
    a.click();
    toast.success("Report downloaded!");
  };

  return (
    <ToolLayout title="IP Blacklist Checker" description="Check if an IP address is listed on 20+ email blacklists">
      <div className="space-y-5 max-w-2xl mx-auto">
        <div className="flex gap-3">
          <Input placeholder="Enter IP address (e.g. 8.8.8.8)" value={ip} onChange={e => setIp(e.target.value)}
            className="rounded-xl flex-1 font-mono" onKeyDown={e => e.key === "Enter" && check()} />
          <Button onClick={check} disabled={loading} className="gradient-bg text-primary-foreground rounded-xl gap-1.5 shrink-0">
            <Shield className="w-4 h-4" /> {loading ? `${progress}%` : "Check"}
          </Button>
        </div>

        {/* Progress */}
        {loading && (
          <div className="w-full bg-muted rounded-full h-2">
            <div className="bg-primary h-2 rounded-full transition-all" style={{ width: `${progress}%` }} />
          </div>
        )}

        {results && (
          <>
            {/* Summary */}
            <div className="grid grid-cols-3 gap-3">
              <div className="bg-green-500/10 rounded-xl p-4 text-center border border-green-500/20">
                <ShieldCheck className="w-6 h-6 mx-auto text-green-600 mb-1" />
                <p className="text-2xl font-bold text-green-600">{clean}</p>
                <p className="text-xs text-muted-foreground">Clean</p>
              </div>
              <div className="bg-destructive/10 rounded-xl p-4 text-center border border-destructive/20">
                <ShieldAlert className="w-6 h-6 mx-auto text-destructive mb-1" />
                <p className="text-2xl font-bold text-destructive">{listed}</p>
                <p className="text-xs text-muted-foreground">Listed</p>
              </div>
              <div className="bg-yellow-500/10 rounded-xl p-4 text-center border border-yellow-500/20">
                <Shield className="w-6 h-6 mx-auto text-yellow-600 mb-1" />
                <p className="text-2xl font-bold text-yellow-600">{timeout}</p>
                <p className="text-xs text-muted-foreground">Timeout</p>
              </div>
            </div>

            {/* Results list */}
            <div className="bg-card rounded-xl border border-border/50 overflow-hidden">
              <div className="p-3 bg-accent/30 border-b border-border/30 flex items-center justify-between">
                <span className="text-xs font-bold">Detailed Results ({results.length}/{knownBlacklists.length})</span>
                <div className="flex gap-2">
                  <Button variant="ghost" size="sm" onClick={exportReport} className="h-7 text-xs gap-1">
                    <Download className="w-3 h-3" /> Export
                  </Button>
                </div>
              </div>
              <div className="divide-y divide-border/20 max-h-96 overflow-y-auto">
                {results.map((r, i) => (
                  <div key={i} className="flex items-center justify-between px-4 py-2.5 hover:bg-accent/10 transition-colors">
                    <div>
                      <span className="text-sm font-medium">{r.name}</span>
                      <span className="text-xs text-muted-foreground ml-2 hidden sm:inline">{r.desc}</span>
                    </div>
                    <span className={`text-xs font-bold px-2.5 py-1 rounded-full ${
                      r.status === "clean" ? "bg-green-500/10 text-green-600" : 
                      r.status === "listed" ? "bg-destructive/10 text-destructive" : 
                      "bg-yellow-500/10 text-yellow-600"}`}>
                      {r.status === "clean" ? "✓ Clean" : r.status === "listed" ? "✗ Listed" : "⏱ Timeout"}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </>
        )}

        <p className="text-xs text-muted-foreground text-center">
          ⚠️ This is a simulated check for demonstration purposes. For real blacklist lookups, use dedicated DNSBL APIs.
        </p>
      </div>
    </ToolLayout>
  );
}
