import { useState, useRef } from "react";
import { ToolLayout } from "@/components/ToolLayout";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export default function StudentIdCard() {
  const [name, setName] = useState("John Doe");
  const [studentId, setStudentId] = useState("STU-2024-001");
  const [department, setDepartment] = useState("Computer Science");
  const [institution, setInstitution] = useState("University of Technology");
  const [session, setSession] = useState("2023-2024");
  const [blood, setBlood] = useState("A+");
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const generate = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    canvas.width = 500;
    canvas.height = 320;
    // BG gradient
    const grad = ctx.createLinearGradient(0, 0, 0, 320);
    grad.addColorStop(0, "#1a237e");
    grad.addColorStop(1, "#283593");
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, 500, 320);
    // White inner
    ctx.fillStyle = "#fff";
    ctx.fillRect(10, 10, 480, 300);
    // Header
    ctx.fillStyle = "#1a237e";
    ctx.fillRect(10, 10, 480, 50);
    ctx.fillStyle = "#fff";
    ctx.font = "bold 16px sans-serif";
    ctx.textAlign = "center";
    ctx.fillText(institution.toUpperCase(), 250, 42);
    // Photo placeholder
    ctx.fillStyle = "#e0e0e0";
    ctx.fillRect(30, 75, 100, 120);
    ctx.fillStyle = "#999";
    ctx.font = "11px sans-serif";
    ctx.fillText("Photo", 80, 140);
    // Details
    ctx.textAlign = "left";
    ctx.fillStyle = "#333";
    ctx.font = "12px sans-serif";
    ctx.fillText(`Name: ${name}`, 150, 95);
    ctx.fillText(`ID: ${studentId}`, 150, 120);
    ctx.fillText(`Department: ${department}`, 150, 145);
    ctx.fillText(`Session: ${session}`, 150, 170);
    ctx.fillText(`Blood Group: ${blood}`, 150, 195);
    // Footer
    ctx.fillStyle = "#1a237e";
    ctx.fillRect(10, 260, 480, 50);
    ctx.fillStyle = "#fff";
    ctx.font = "10px sans-serif";
    ctx.textAlign = "center";
    ctx.fillText("STUDENT IDENTITY CARD — Generated by WebTools", 250, 290);
  };

  const download = () => {
    generate();
    setTimeout(() => {
      const link = document.createElement("a");
      link.download = "student-id-card.png";
      link.href = canvasRef.current?.toDataURL() || "";
      link.click();
    }, 100);
  };

  return (
    <ToolLayout title="Student ID Card Maker" description="Create student ID cards easily">
      <div className="space-y-5 max-w-lg mx-auto">
        <Input value={institution} onChange={(e) => setInstitution(e.target.value)} placeholder="Institution Name" className="rounded-xl" />
        <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Student Name" className="rounded-xl" />
        <Input value={studentId} onChange={(e) => setStudentId(e.target.value)} placeholder="Student ID" className="rounded-xl" />
        <Input value={department} onChange={(e) => setDepartment(e.target.value)} placeholder="Department" className="rounded-xl" />
        <div className="grid grid-cols-2 gap-3">
          <Input value={session} onChange={(e) => setSession(e.target.value)} placeholder="Session" className="rounded-xl" />
          <Input value={blood} onChange={(e) => setBlood(e.target.value)} placeholder="Blood Group" className="rounded-xl" />
        </div>
        <div className="flex gap-3">
          <Button onClick={generate} className="gradient-bg text-primary-foreground rounded-xl font-semibold">Preview</Button>
          <Button onClick={download} variant="outline" className="rounded-xl">Download</Button>
        </div>
        <canvas ref={canvasRef} className="w-full rounded-2xl border border-border" />
      </div>
    </ToolLayout>
  );
}
